Addressed dp overlap with mem, compute slowdown
paragraph-sim/calculon pull request #21
Opened 2023-03-17 15:23 UTC by michael-isaev

2023-03-17 23:12 UTC, nicmcd requested changes

2023-03-17 23:12 UTC, nicmcd commented on calculon/megatron/megatron.py
> +      self.data_par_comm_resource = cfg['data_par_comm_resource']
This needs a range check
should be >= 0.0 and < 1.0

2023-03-17 23:12 UTC, nicmcd commented on calculon/megatron/optimal_execution.py
> +                              'data_par_comm_resource': 0.02,
This doesn't really work in this case. The optimal execution engine tries all networks for DP. If DP gets mapped to network 1 (i.e., NVLink) then the # of SMs would be larger (e.g., 8-16 ish). However, if it gets mapped to network 2 (i.e., InfiniBand) then the # of SMs would be small (e.g. 2).

2023-03-18 17:16 UTC, michael-isaev commented on calculon/megatron/optimal_execution.py
> +                              'data_par_comm_resource': 0.02,
Oh, that's a great catch!
I had an idea that if you need 2 SMs for 50 GB/s IB less efficiency, then you should use multiply more SMs for NVLink 450 GB/s, less efficiency. You could probably have some scale stemming from some system parameter, e.g. how much bandwidth can single SM utilize, but that's not information that's easy to get - I didn't see many such benchmark examples.
I can transfer this parameter to system/network and call it something like `proc_utilization`

2023-03-18 17:16 UTC, michael-isaev commented on calculon/megatron/megatron.py
> +      self.data_par_comm_resource = cfg['data_par_comm_resource']
agreed, will do

2023-03-18 21:48 UTC, nicmcd commented on calculon/megatron/optimal_execution.py
> +                              'data_par_comm_resource': 0.02,
Wait on the changes, lets talk next week

2023-03-20 16:03 UTC, nicmcd commented on calculon/megatron/optimal_execution.py
> +                              'data_par_comm_resource': 0.02,
After further though, I think this should be a member of the system configuration listed under each network.

2023-03-20 20:10 UTC, nicmcd approved these changes

2023-03-20 20:10 UTC, merged