Redone act computation to improve accuracy
paragraph-sim/calculon pull request #23
Opened 2023-03-22 00:42 UTC by michael-isaev

2023-03-22 15:50 UTC, nicmcd requested changes

2023-03-22 15:50 UTC, nicmcd commented on calculon/megatron/layers.py
> +               activation_not_stored=False, output_not_stored=False):
Having a boolean variable include the word "not" is almost always a bad idea. Nearly every style guide will urge not to do this. Instead of `activation_not_stored=False`, you should do `activation_stored=True`.

2023-03-22 15:52 UTC, nicmcd requested changes

2023-03-22 15:52 UTC, nicmcd commented on calculon/util.py
> +    step = 1024
1024???

2023-03-22 17:01 UTC, michael-isaev commented on calculon/util.py
> +    step = 1024
Yup, because i have printing of raw parameters before their multiplication by bytes they store, and seeing MiB is confusing, while seeing non power of 2 will be annoying. For non-1024 case we have "None" as type

2023-03-22 19:49 UTC, michael-isaev commented on calculon/megatron/layers.py
> +               activation_not_stored=False, output_not_stored=False):
done

2023-03-22 22:57 UTC, nicmcd approved these changes

2023-03-23 00:58 UTC, nicmcd approved these changes

2023-03-23 00:58 UTC, merged